Console.WriteLine("   _____");
Console.WriteLine("  /     \\");
Console.Write("/- (");
Console.ForegroundColor = ConsoleColor.Green;
Console.Write("*");
Console.ResetColor();
Console.Write(") |");
Console.ForegroundColor = ConsoleColor.Green;
Console.Write("*");
Console.ResetColor();
Console.WriteLine(")\\");
Console.WriteLine("|/\\.  _>/\\|");
Console.WriteLine("    \\__/    |\\");
Console.WriteLine("   _| |_   \\-/");
Console.Write("  /");
Console.ForegroundColor = ConsoleColor.Magenta;
Console.Write("|\\__|");
Console.ResetColor();
Console.WriteLine("\\  //");
Console.Write(" |/");
Console.ForegroundColor = ConsoleColor.Magenta;
Console.Write("|   |");
Console.ResetColor();
Console.WriteLine("\\\\//");
Console.Write(" ||");
Console.ForegroundColor = ConsoleColor.Magenta;
Console.Write("|   |");
Console.ResetColor();
Console.WriteLine(" ~'");
Console.Write(" ||");
Console.ForegroundColor = ConsoleColor.Magenta;
Console.WriteLine("| __|");
Console.ResetColor();
Console.WriteLine(" /_\\| ||");
Console.WriteLine(" \\_/| ||");
Console.WriteLine("   |7 |7");
Console.WriteLine("   || ||");
Console.WriteLine("   || ||");
Console.WriteLine("   /\\ \\ \\ ");
Console.WriteLine("  ^^^^ ^^^");

